apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd                
spec:
  project: default
  destination:
    namespace: testing
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 18.0.0           
    helm:
      values: |
        replicaCount: 2
        service:
          type: ClusterIP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        metrics:
          enabled: true
  syncPolicy:
    automated:                       
      prune: true
      selfHeal: true
